services:
  gemma_bot:
    build: .
    network_mode: "host"   # Necesario para que localhost:11434 apunte a LM Studio en tu PC
    environment:
      - API_ID=
      - API_HASH=
      - BOT_TOKEN=
      - MODEL_NAME=gemma-4-26b-a4b-it-uncensored
    restart: unless-stopped
